SELECT * FROM tbcliente;

SELECT DNI,NOMBRE,DIRECCION1,DIRECCION2,BARRIO,CIUDAD,ESTADO,CP,FECHA_NACIMIENTO,EDAD,
SEXO,LIMITE_CREDITO,VOLUMEN_COMPRA,PRIMERA_COMPRA FROM tbcliente;

SELECT DNI,NOMBRE from tbcliente;

SELECT NOMBRE as Nombre_Completo, SEXO as Genero, EDAD as Años from tbcliente LIMIT 10;