USE jugos;

ALTER TABLE tbclientes ADD PRIMARY KEY (DNI);

ALTER TABLE tbclientes ADD COLUMN(FECHA_NACIMIENTO DATE);

INSERT INTO tbclientes(DNI,
NOMBRE,
DIRECCION1,
DIRECCION2 ,
BARRIO,
CIUDAD,
ESTADO,
CP,
EDAD,
SEXO,
LIMITE_CREDITO,
VOLUMEN_COMPRA,
PRIMERA_COMPRA,
FECHA_NACIMIENTO) VALUES (1036666576, 'Starleen Gaviria','Calle 8 a sur',
'','Guayabal San Rafael','Medellin','Antioquia','50001',
29,'M',1000000,2000,0,'1996-05-20');

SELECT * FROM tbclientes